In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

In [3]:
import subprocess, sys
for pkg in ['psycopg2-binary', 'sqlalchemy']:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg, '-q'])
print("✅ PostgreSQL packages installed successfully!")

✅ PostgreSQL packages installed successfully!

In [6]:
# ---- PostgreSQL connection ----

PG_USER = "postgres"
PG_PASSWORD = "admin123"
PG_HOST = "localhost"
PG_PORT = "5432"
PG_DATABASE = "amazon_india_db"   


db = create_engine(
    f"postgresql+psycopg2://{PG_USER}:{PG_PASSWORD}@{PG_HOST}:{PG_PORT}/{PG_DATABASE}"
)

# quick connectivity check
with db.connect() as conn:
    print("Connected to:", conn.execute(text("SELECT version();")).scalar())

Connected to: PostgreSQL 17.5 on x86_64-windows, compiled by msvc-19.44.35209, 64-bit

In [7]:
CLEANED_DATA_PATH = r'./data/cleaned/amazon_india_cleaned.csv'

df = pd.read_csv(CLEANED_DATA_PATH, low_memory=False, parse_dates=['order_date'])
print("Rows loaded:", len(df))
df.head()

Rows loaded: 1127609

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating,is_potential_duplicate
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7,False
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,No Festival,4.5,Delivered,1,2015,1,0.20,True,4.1,False
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,Republic Day Sale,4.3,Delivered,1,2015,1,0.17,True,3.3,False
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,21947.26,0.00,...,No Festival,3.0,Delivered,1,2015,1,0.22,True,3.5,False
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,No Festival,4.0,Delivered,1,2015,1,0.20,True,4.1,False

In [8]:
df.shape

(1127609, 35)

In [9]:
# Split out the mis-combined product-catalog rows (no transaction_id) from real transactions
catalog_rows = df[df['transaction_id'].isna()].copy()
txn = df[df['transaction_id'].notna()].copy()

print("Product-catalog-only rows (no transaction_id):", len(catalog_rows))
print("Actual transaction rows:", len(txn))

Product-catalog-only rows (no transaction_id): 0
Actual transaction rows: 1127609

In [11]:
import pandas as pd
from sqlalchemy import create_engine

# Step 1: Connect to your local PostgreSQL database
db_url = "postgresql+psycopg2://postgres:admin123@localhost:5432/amazon_india_db"
engine = create_engine(db_url)
print("Connected to PostgreSQL successfully!")

# Step 2: Build the Products Dimension table using your friend's logic
products = txn.groupby('product_id').agg(
    product_name=('product_name', 'first'),
    category=('category', 'first'),
    subcategory=('subcategory', 'first'),
    brand=('brand', 'first'),
    product_weight_kg=('product_weight_kg', 'first'),
    product_rating=('product_rating', 'first'),
    is_prime_eligible=('is_prime_eligible', 'first'),
).reset_index()

print("Products Dimension shape:", products.shape)

# Step 3: Build the Customers Dimension table using your friend's logic
customers = txn.groupby('customer_id').agg(
    customer_city=('customer_city', 'first'),
    customer_state=('customer_state', 'first'),
    customer_tier=('customer_tier', 'first'),
    customer_spending_tier=('customer_spending_tier', 'last'),
    customer_age_group=('customer_age_group', 'first'),
    is_prime_member=('is_prime_member', 'last'),
).reset_index()

print("Customers Dimension shape:", customers.shape)

Connected to PostgreSQL successfully!
Products Dimension shape: (2004, 8)
Customers Dimension shape: (354969, 7)

In [12]:
# Step 4: Build the Time Dimension table using your friend's logic
dates = txn['order_date'].dropna().drop_duplicates().sort_values().reset_index(drop=True)

time_dim = pd.DataFrame({'full_date': dates})
time_dim['date_id']    = time_dim['full_date'].dt.strftime('%Y%m%d').astype(int)
time_dim['year']       = time_dim['full_date'].dt.year
time_dim['month']      = time_dim['full_date'].dt.month
time_dim['month_name'] = time_dim['full_date'].dt.month_name()
time_dim['quarter']    = time_dim['full_date'].dt.quarter
time_dim['day']        = time_dim['full_date'].dt.day
time_dim['day_name']   = time_dim['full_date'].dt.day_name()
time_dim['is_weekend'] = time_dim['full_date'].dt.dayofweek >= 5

time_dim = time_dim[['date_id', 'full_date', 'year', 'month', 'month_name',
                      'quarter', 'day', 'day_name', 'is_weekend']]

print("Time Dimension shape:", time_dim.shape)

# Step 5: Build the Transactions Fact table using your friend's logic
transactions = txn.copy()
transactions['date_id'] = pd.to_numeric(transactions['order_date'].dt.strftime('%Y%m%d'), errors='coerce')

fact_cols = ['transaction_id', 'date_id', 'customer_id', 'product_id',
             'original_price_inr', 'discount_percent', 'discounted_price_inr',
             'quantity', 'subtotal_inr', 'delivery_charges', 'final_amount_inr',
             'payment_method', 'delivery_days', 'delivery_type',
             'is_festival_sale', 'festival_name', 'customer_rating', 'return_status']

transactions = transactions[fact_cols]

# Clean up quantity and drop rows with missing foreign keys
transactions['quantity'] = pd.to_numeric(transactions['quantity'], errors='coerce').astype('Int64')
transactions = transactions.dropna(subset=['date_id', 'customer_id', 'product_id'])
transactions['date_id'] = transactions['date_id'].astype(int)

print("Transactions Fact shape:", transactions.shape)

Time Dimension shape: (4015, 9)
Transactions Fact shape: (1019353, 18)

In [13]:
# Step 6: Export all cleaned tables into PostgreSQL using chunking for large data
print("Uploading tables to PostgreSQL in batches...")

# We use chunksize=10000 so large tables (like 1M+ transactions) upload smoothly without freezing
products.to_sql("dim_products", con=engine, if_exists="replace", index=False, chunksize=10000)
customers.to_sql("dim_customers", con=engine, if_exists="replace", index=False, chunksize=10000)
time_dim.to_sql("dim_time", con=engine, if_exists="replace", index=False, chunksize=10000)
transactions.to_sql("fact_sales", con=engine, if_exists="replace", index=False, chunksize=10000)

print("SUCCESS: All 4 tables are live, chunked, and populated in PostgreSQL!")

Uploading tables to PostgreSQL in batches...
SUCCESS: All 4 tables are live, chunked, and populated in PostgreSQL!

In [14]:
import pandas as pd
from sqlalchemy import create_engine

# Connect to your database
engine = create_engine("postgresql+psycopg2://postgres:admin123@localhost:5432/amazon_india_db")

# Check table names and row counts
query = """
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public';
"""
tables = pd.read_sql(query, con=engine)
print("Tables in database:\n", tables)

# Quick preview of your fact table row count
print("\nTotal rows in fact_sales:", pd.read_sql("SELECT COUNT(*) FROM fact_sales;", con=engine).iloc[0, 0])

Tables in database:
       table_name
0   dim_products
1  dim_customers
2       dim_time
3     fact_sales

Total rows in fact_sales: 1019353

In [5]:
# ---------- PRODUCTS dimension ----------
prod_from_txn = txn.groupby('product_id').agg(
    product_name=('product_name', 'first'),
    category=('category', 'first'),
    subcategory=('subcategory', 'first'),
    brand=('brand', 'first'),
    product_weight_kg=('product_weight_kg', 'first'),
    product_rating=('product_rating', 'first'),
    is_prime_eligible=('is_prime_eligible', 'first'),
).reset_index()

catalog = catalog_rows[['product_id', 'base_price_2015', 'weight_kg', 'rating',
                         'launch_year', 'model']].drop_duplicates('product_id')

products = prod_from_txn.merge(catalog, on='product_id', how='left')
print("products:", products.shape)
products.head()

products: (2004, 13)

,product_id,product_name,category,subcategory,brand,product_weight_kg,product_rating,is_prime_eligible,base_price_2015,weight_kg,rating,launch_year,model
0,PROD_000001,Apple iPhone 6 16GB Black,Electronics & Accessories,Smartphones,Apple,0.21,3.9,True,190469.10,0.21,3.9,2015.0,iPhone 6
1,PROD_000002,Apple iPhone 6 32GB Black,Electronics & Accessories,Smartphones,Apple,0.18,3.4,True,158424.89,0.18,3.4,2015.0,iPhone 6
2,PROD_000003,Apple iPhone 6 64GB Black,Electronics & Accessories,Smartphones,Apple,0.22,4.6,True,118141.16,0.22,4.6,2015.0,iPhone 6
3,PROD_000004,Apple iPhone 6 16GB White,Electronics & Accessories,Smartphones,Apple,0.21,4.1,True,211721.16,0.21,4.1,2015.0,iPhone 6
4,PROD_000005,Apple iPhone 6 32GB White,Electronics & Accessories,Smartphones,Apple,0.20,3.8,True,114806.24,0.20,3.8,2015.0,iPhone 6

In [6]:
# ---------- CUSTOMERS dimension ----------
customers = txn.groupby('customer_id').agg(
    customer_city=('customer_city', 'first'),
    customer_state=('customer_state', 'first'),
    customer_tier=('customer_tier', 'first'),
    customer_spending_tier=('customer_spending_tier', 'last'),
    customer_age_group=('customer_age_group', 'first'),
    is_prime_member=('is_prime_member', 'last'),
).reset_index()
print("customers:", customers.shape)
customers.head()

customers: (354969, 7)

,customer_id,customer_city,customer_state,customer_tier,customer_spending_tier,customer_age_group,is_prime_member
0,CUST_2015_00000001,Mumbai,Maharashtra,Metro,Budget,26-35,False
1,CUST_2015_00000002,Allahabad,Uttar Pradesh,Rural,Standard,36-45,False
2,CUST_2015_00000003,Bangalore,Karnataka,Metro,Standard,26-35,False
3,CUST_2015_00000004,Mumbai,Maharashtra,Metro,Standard,55+,False
4,CUST_2015_00000005,Jaipur,Rajasthan,Tier1,Standard,26-35,False

In [7]:
# ---------- TIME DIMENSION ----------
dates = txn['order_date'].dropna().drop_duplicates().sort_values().reset_index(drop=True)

time_dim = pd.DataFrame({'full_date': dates})
time_dim['date_id']    = time_dim['full_date'].dt.strftime('%Y%m%d').astype(int)
time_dim['year']       = time_dim['full_date'].dt.year
time_dim['month']      = time_dim['full_date'].dt.month
time_dim['month_name'] = time_dim['full_date'].dt.month_name()
time_dim['quarter']    = time_dim['full_date'].dt.quarter
time_dim['day']        = time_dim['full_date'].dt.day
time_dim['day_name']   = time_dim['full_date'].dt.day_name()
time_dim['is_weekend'] = time_dim['full_date'].dt.dayofweek >= 5

time_dim = time_dim[['date_id', 'full_date', 'year', 'month', 'month_name',
                      'quarter', 'day', 'day_name', 'is_weekend']]
print("time_dimension:", time_dim.shape)
time_dim.head()

time_dimension: (4015, 9)

,date_id,full_date,year,month,month_name,quarter,day,day_name,is_weekend
0,20150101,2015-01-01,2015,1,January,1,1,Thursday,False
1,20150102,2015-01-02,2015,1,January,1,2,Friday,False
2,20150103,2015-01-03,2015,1,January,1,3,Saturday,True
3,20150104,2015-01-04,2015,1,January,1,4,Sunday,True
4,20150105,2015-01-05,2015,1,January,1,5,Monday,False

In [ ]:
# ---------- TRANSACTIONS fact table ----------
transactions = txn.copy()
transactions['date_id'] = pd.to_numeric(transactions['order_date'].dt.strftime('%Y%m%d'), errors='coerce')

fact_cols = ['transaction_id', 'date_id', 'customer_id', 'product_id',
             'original_price_inr', 'discount_percent', 'discounted_price_inr',
             'quantity', 'subtotal_inr', 'delivery_charges', 'final_amount_inr',
             'payment_method', 'delivery_days', 'delivery_type',
             'is_festival_sale', 'festival_name', 'customer_rating', 'return_status']

transactions = transactions[fact_cols]

# quantity must be a clean integer for the SQL INTEGER column
transactions['quantity'] = pd.to_numeric(transactions['quantity'], errors='coerce').astype('Int64')

# drop any rows that would violate the foreign keys (missing date/customer/product)
transactions = transactions.dropna(subset=['date_id', 'customer_id', 'product_id'])
transactions['date_id'] = transactions['date_id'].astype(int)

print("transactions (fact):", transactions.shape)
transactions.head()

transactions (fact): (1014324, 18)

,transaction_id,date_id,customer_id,product_id,original_price_inr,discount_percent,discounted_price_inr,quantity,subtotal_inr,delivery_charges,final_amount_inr,payment_method,delivery_days,delivery_type,is_festival_sale,festival_name,customer_rating,return_status
0,TXN_2015_00000001,20150125,CUST_2015_00003884,PROD_000021,123614.29,27.91,89112.17,1,89112.17,0.0,89112.17,COD,6.0,Standard,True,Republic Day Sale,5.0,Delivered
1,TXN_2015_00000002,20150105,CUST_2015_00011709,PROD_000055,54731.86,0.00,54731.86,1,54731.86,0.0,54731.86,COD,4.0,Standard,False,NaN,4.5,Delivered
2,TXN_2015_00000003,20150124,CUST_2015_00004782,PROD_000039,97644.25,46.93,51818.26,2,103636.52,NaN,103636.52,COD,4.0,Standard,True,Republic Day Sale,NaN,Delivered
3,TXN_2015_00000004,20150128,CUST_2015_00008105,PROD_000085,21947.26,0.00,21947.26,1,21947.26,0.0,21947.26,COD,4.0,Standard,False,NaN,3.0,Delivered
4,TXN_2015_00000005,20150131,CUST_2015_00002955,PROD_000055,54731.86,0.00,54731.86,2,109463.72,0.0,109463.72,COD,3.0,Standard,False,NaN,4.0,Delivered

CREATE POSTGRESQL SCHEMA(ddl)

In [9]:
DDL = """
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS time_dimension CASCADE;

CREATE TABLE customers (
    customer_id             VARCHAR(30) PRIMARY KEY,
    customer_city           VARCHAR(50),
    customer_state          VARCHAR(50),
    customer_tier           VARCHAR(20),
    customer_spending_tier  VARCHAR(20),
    customer_age_group      VARCHAR(20),
    is_prime_member         BOOLEAN
);

CREATE TABLE products (
    product_id           VARCHAR(30) PRIMARY KEY,
    product_name          VARCHAR(200),
    category               VARCHAR(60),
    subcategory            VARCHAR(60),
    brand                   VARCHAR(60),
    product_weight_kg      NUMERIC(8,3),
    product_rating          NUMERIC(3,2),
    is_prime_eligible       BOOLEAN,
    base_price_2015         NUMERIC(12,2),
    weight_kg               NUMERIC(8,3),
    rating                   NUMERIC(3,2),
    launch_year              INT,
    model                     VARCHAR(100)
);

CREATE TABLE time_dimension (
    date_id      INT PRIMARY KEY,
    full_date    DATE NOT NULL,
    year         INT,
    month        INT,
    month_name   VARCHAR(15),
    quarter      INT,
    day          INT,
    day_name     VARCHAR(15),
    is_weekend   BOOLEAN
);

CREATE TABLE transactions (
    transaction_id         VARCHAR(30) PRIMARY KEY,
    date_id                 INT REFERENCES time_dimension(date_id),
    customer_id              VARCHAR(30) REFERENCES customers(customer_id),
    product_id                VARCHAR(30) REFERENCES products(product_id),
    original_price_inr        NUMERIC(12,2),
    discount_percent          NUMERIC(5,2),
    discounted_price_inr      NUMERIC(12,2),
    quantity                   INT,
    subtotal_inr                NUMERIC(14,2),
    delivery_charges             NUMERIC(10,2),
    final_amount_inr              NUMERIC(14,2),
    payment_method                 VARCHAR(40),
    delivery_days                   NUMERIC(5,1),
    delivery_type                    VARCHAR(30),
    is_festival_sale                  BOOLEAN,
    festival_name                      VARCHAR(50),
    customer_rating                     NUMERIC(3,2),
    return_status                        VARCHAR(30)
);
"""

with db.begin() as conn:
    for stmt in DDL.split(";"):
        if stmt.strip():
            conn.execute(text(stmt))

print("Schema created: customers, products, time_dimension, transactions")

Schema created: customers, products, time_dimension, transactions

LOADING THE DATA TO POSTGRESQL

In [10]:
customers.to_sql('customers', db, if_exists='append', index=False, method='multi', chunksize=5000)
print("customers loaded:", len(customers))

products.to_sql('products', db, if_exists='append', index=False, method='multi', chunksize=5000)
print("products loaded:", len(products))

time_dim.to_sql('time_dimension', db, if_exists='append', index=False, method='multi', chunksize=5000)
print("time_dimension loaded:", len(time_dim))

customers loaded: 354969
products loaded: 2004
time_dimension loaded: 4015

In [ ]:
#transactions.to_sql('transactions', db, if_exists='append', index=False, method='multi', chunksize=2000)
#print("transactions:", len(transactions))

In [13]:
# Fast bulk load for the large fact table using COPY (much faster than to_sql for ~1M+ rows)
import io

# clear out any previous load first, so re-running this cell is safe
with db.begin() as conn:
    conn.execute(text("TRUNCATE TABLE transactions;"))

buffer = io.StringIO()
transactions.to_csv(buffer, index=False, header=False)
buffer.seek(0)

raw_conn = db.raw_connection()
try:
    cursor = raw_conn.cursor()
    cursor.copy_expert(
        "COPY transactions FROM STDIN WITH (FORMAT csv)",
        buffer
    )
    raw_conn.commit()
finally:
    raw_conn.close()

print("transactions loaded:", len(transactions))

transactions loaded: 1014324

In [14]:
INDEXES = """
CREATE INDEX IF NOT EXISTS idx_txn_date         ON transactions(date_id);
CREATE INDEX IF NOT EXISTS idx_txn_customer     ON transactions(customer_id);
CREATE INDEX IF NOT EXISTS idx_txn_product      ON transactions(product_id);
CREATE INDEX IF NOT EXISTS idx_txn_payment      ON transactions(payment_method);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_customers_state   ON customers(customer_state);
CREATE INDEX IF NOT EXISTS idx_time_year_month   ON time_dimension(year, month);
"""

with db.begin() as conn:
    for stmt in INDEXES.split(";"):
        if stmt.strip():
            conn.execute(text(stmt))
    conn.execute(text("ANALYZE;"))

print("Indexes created")

Indexes created

In [15]:
validation = pd.read_sql(text('''
    SELECT
      (SELECT COUNT(*) FROM customers)      AS customers_rows,
      (SELECT COUNT(*) FROM products)       AS products_rows,
      (SELECT COUNT(*) FROM time_dimension) AS time_dimension_rows,
      (SELECT COUNT(*) FROM transactions)   AS transactions_rows
'''), db)
validation

   customers_rows  products_rows  time_dimension_rows  transactions_rows
0          354969           2004                 4015            1014324

In [16]:
orphans = pd.read_sql(text('''
    SELECT
      (SELECT COUNT(*) FROM transactions t LEFT JOIN customers c ON t.customer_id=c.customer_id WHERE c.customer_id IS NULL) AS orphan_customers,
      (SELECT COUNT(*) FROM transactions t LEFT JOIN products p ON t.product_id=p.product_id WHERE p.product_id IS NULL) AS orphan_products,
      (SELECT COUNT(*) FROM transactions t LEFT JOIN time_dimension td ON t.date_id=td.date_id WHERE td.date_id IS NULL) AS orphan_dates
'''), db)
orphans

   orphan_customers  orphan_products  orphan_dates
0                 0                0             0

Question 1
Create an Executive Summary Dashboard showing key business metrics: Total Revenue, Growth Rate, Active Customers, Average Order Value, and Top Performing Categories. Include year-over-year comparisons and trend indicators.

In [18]:
q1 = pd.read_sql(text('''
    WITH yearly_revenue AS (
        SELECT 
            td.year,
            SUM(t.final_amount_inr) AS total_revenue
        FROM transactions t
        JOIN time_dimension td ON t.date_id = td.date_id
        GROUP BY td.year
    )
    SELECT 
        year,
        ROUND(total_revenue, 2) AS total_revenue,
        ROUND(
            100.0 * (total_revenue - LAG(total_revenue) OVER (ORDER BY year)) 
            / NULLIF(LAG(total_revenue) OVER (ORDER BY year), 0), 
            2
        ) AS growth_pct
    FROM yearly_revenue
    ORDER BY year;
'''), db)
q1

    year  total_revenue  growth_pct
0   2015   1.913086e+09         NaN
1   2016   3.232041e+09       68.94
2   2017   4.946704e+09       53.05
3   2018   6.508979e+09       31.58
4   2019   7.739441e+09       18.90
5   2020   1.067302e+10       37.90
6   2021   9.886130e+09       -7.37
7   2022   7.662716e+09      -22.49
8   2023   6.933545e+09       -9.52
9   2024   6.147703e+09      -11.33
10  2025   3.457024e+09      -43.77

Question 2
Build a Real-time Business Performance Monitor displaying current month performance vs targets, revenue run-rate, customer acquisition metrics, and key operational indicators with alerts for underperformance.

In [19]:
q2 = pd.read_sql(text('''
    SELECT td.year, td.month, ROUND(SUM(t.final_amount_inr),2) AS revenue
    FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
    GROUP BY td.year, td.month
    ORDER BY td.year, td.month
'''), db)
q2.head()

   year  month       revenue
0  2015      1  1.446325e+08
1  2015      2  1.291355e+08
2  2015      3  1.319491e+08
3  2015      4  1.562460e+08
4  2015      5  1.384932e+08

Question 3
Design a Strategic Overview Dashboard showing market share analysis, competitive positioning, geographic expansion metrics, and business health indicators for C-level decision making.

In [20]:
q3 = pd.read_sql(text('''
    WITH ref AS (
        SELECT MAX(td.full_date) AS max_date
        FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
    ),
    rfm AS (
        SELECT t.customer_id,
               (SELECT max_date FROM ref) - MAX(td.full_date) AS recency_days,
               COUNT(DISTINCT t.transaction_id) AS frequency,
               SUM(t.final_amount_inr) AS monetary
        FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
        GROUP BY t.customer_id
    )
    SELECT customer_id, recency_days, frequency, ROUND(monetary,2) AS monetary,
           NTILE(4) OVER (ORDER BY recency_days DESC) AS r_score,
           NTILE(4) OVER (ORDER BY frequency)         AS f_score,
           NTILE(4) OVER (ORDER BY monetary)          AS m_score
    FROM rfm
'''), db)
q3.head()

,customer_id,recency_days,frequency,monetary,r_score,f_score,m_score
0,CUST_2015_00002956,4014,1,11833.24,1,1,1
1,CUST_2015_00001232,4009,1,33199.84,1,1,1
2,CUST_2015_00011945,4002,1,89660.80,1,2,2
3,CUST_2015_00011231,3999,1,24762.02,1,1,1
4,CUST_2015_00000162,3993,1,8670.38,1,1,1

Question 4
Create a Financial Performance Dashboard with revenue breakdown by categories, profit margin analysis, cost structure visualization, and financial forecasting models.

In [21]:
q4 = pd.read_sql(text('''
    SELECT td.year, t.payment_method,
           ROUND(SUM(t.final_amount_inr),2) AS revenue,
           COUNT(*) AS txn_count
    FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
    GROUP BY td.year, t.payment_method
    ORDER BY td.year, revenue DESC
'''), db)
q4.head(10)

   year        payment_method       revenue  txn_count
0  2015                   COD  1.437631e+09      22422
1  2015  Cards (Credit/Debit)  3.824661e+08       5919
2  2015           Net Banking  9.298932e+07       1421
3  2016                   COD  2.269119e+09      34860
4  2016  Cards (Credit/Debit)  7.722378e+08      11921
5  2016           Net Banking  1.253039e+08       1936
6  2016                   UPI  6.537984e+07       1019
7  2017                   COD  2.972815e+09      41815
8  2017  Cards (Credit/Debit)  1.378144e+09      19454
9  2017                   UPI  3.499269e+08       4894

Question 5
Build a Growth Analytics Dashboard tracking customer growth, market penetration, product portfolio expansion, and strategic initiative performance with predictive insights.

In [22]:
q5 = pd.read_sql(text('''
    SELECT p.category,
           ROUND(SUM(t.final_amount_inr),2) AS revenue,
           ROUND(100.0*SUM(t.final_amount_inr)/SUM(SUM(t.final_amount_inr)) OVER(),2) AS market_share_pct
    FROM transactions t JOIN products p ON t.product_id = p.product_id
    GROUP BY p.category
    ORDER BY revenue DESC
'''), db)
q5

                    category       revenue  market_share_pct
0  Electronics & Accessories  6.910039e+10             100.0

In [23]:
q5 = pd.read_sql(text('''
    SELECT p.category,
           p.subcategory,
           ROUND(SUM(t.final_amount_inr), 2) AS revenue,
           ROUND(100.0 * SUM(t.final_amount_inr) / SUM(SUM(t.final_amount_inr)) OVER(), 2) AS market_share_pct
    FROM transactions t 
    JOIN products p ON t.product_id = p.product_id
    GROUP BY p.category, p.subcategory
    ORDER BY p.category ASC, revenue DESC
'''), db)
q5

,category,subcategory,revenue,market_share_pct
0,Electronics & Accessories,Smartphones,5.046127e+10,73.03
1,Electronics & Accessories,Laptops,8.441863e+09,12.22
2,Electronics & Accessories,Tablets,4.581514e+09,6.63
3,Electronics & Accessories,Smart Watch,2.883738e+09,4.17
4,Electronics & Accessories,TV & Entertainment,1.730468e+09,2.50
5,Electronics & Accessories,Audio,1.001527e+09,1.45

Question 6
Design a Revenue Trend Analysis Dashboard showing monthly/quarterly/yearly revenue patterns, growth rates, seasonal variations, and revenue forecasting with interactive time period selection.

In [24]:
q6 = pd.read_sql(text('''
    SELECT c.is_prime_member,
           ROUND(AVG(t.final_amount_inr),2) AS avg_order_value,
           COUNT(*) AS orders,
           COUNT(DISTINCT t.customer_id) AS customers
    FROM transactions t JOIN customers c ON t.customer_id = c.customer_id
    GROUP BY c.is_prime_member
'''), db)
q6

   is_prime_member  avg_order_value  orders  customers
0            False         61942.58  628281     189787
1             True         78185.69  386043     155576

Question 7
Create a Category Performance Dashboard analyzing revenue contribution, growth trends, market share changes, and category-wise profitability with drill-down capabilities.

In [25]:
q7 = pd.read_sql(text('''
    SELECT c.customer_tier,
           ROUND(SUM(t.final_amount_inr),2) AS revenue,
           COUNT(DISTINCT c.customer_id) AS customers
    FROM transactions t JOIN customers c ON t.customer_id = c.customer_id
    GROUP BY c.customer_tier
    ORDER BY revenue DESC
'''), db)
q7

  customer_tier       revenue  customers
0         Metro  3.814137e+10     163987
1         Tier1  1.993185e+10     107703
2         Tier2  8.938804e+09      56788
3         Rural  2.088359e+09      16885

Question 8
Build a Geographic Revenue Analysis showing state-wise and city-wise performance, tier-wise growth patterns, and market penetration opportunities with interactive maps.

In [26]:
q8 = pd.read_sql(text('''
    SELECT t.is_festival_sale,
           ROUND(SUM(t.final_amount_inr),2) AS revenue,
           COUNT(*) AS txns,
           ROUND(AVG(t.final_amount_inr),2) AS avg_order_value
    FROM transactions t
    GROUP BY t.is_festival_sale
'''), db)
q8

   is_festival_sale       revenue    txns  avg_order_value
0             False  5.416717e+10  699535         77433.11
1              True  1.493322e+10  314789         47438.82

Question 9
Design a Festival Sales Analytics Dashboard tracking festival period performance, campaign effectiveness, promotional impact, and seasonal revenue optimization insights.

In [27]:
q9 = pd.read_sql(text('''
    SELECT c.customer_age_group,
           ROUND(AVG(t.final_amount_inr),2) AS avg_spend,
           COUNT(*) AS orders
    FROM transactions t JOIN customers c ON t.customer_id = c.customer_id
    GROUP BY c.customer_age_group
    ORDER BY avg_spend DESC
'''), db)
q9

  customer_age_group  avg_spend  orders
0              26-35   68231.51  351436
1              18-25   68215.75  319419
2              36-45   68065.23  200655
3              46-55   67988.28   99869
4                55+   67632.39   30335
5               None   66042.18   12610

Question 10
Create a Price Optimization Dashboard analyzing price elasticity, discount effectiveness, competitive pricing, and revenue impact of pricing strategies.

In [28]:
q10 = pd.read_sql(text('''
    SELECT ROUND(CORR(t.original_price_inr, t.quantity)::numeric,4) AS price_qty_correlation
    FROM transactions t
    WHERE t.original_price_inr IS NOT NULL AND t.quantity IS NOT NULL
'''), db)
q10

   price_qty_correlation
0                 0.0008

Question 11
Build a Customer Segmentation Dashboard using RFM analysis, behavioral segmentation, lifetime value analysis, and targeted marketing recommendations with interactive customer profiles.

In [29]:
q11 = pd.read_sql(text('''
    SELECT c.customer_tier,
           ROUND(AVG(t.delivery_days),2) AS avg_delivery_days,
           ROUND(AVG(t.customer_rating),2) AS avg_rating
    FROM transactions t JOIN customers c ON t.customer_id = c.customer_id
    WHERE t.delivery_days IS NOT NULL
    GROUP BY c.customer_tier
'''), db)
q11

  customer_tier  avg_delivery_days  avg_rating
0         Metro               3.37        4.33
1         Rural               3.47        4.23
2         Tier1               3.25        4.30
3         Tier2               3.34        4.27

Question 12
Design a Customer Journey Analytics Dashboard tracking acquisition channels, purchase patterns, category transitions, and customer evolution from first-time to loyal customers.

In [30]:
q12 = pd.read_sql(text('''
    SELECT t.return_status,
           COUNT(*) AS cnt,
           ROUND(AVG(t.customer_rating),2) AS avg_rating,
           ROUND(AVG(t.final_amount_inr),2) AS avg_amount
    FROM transactions t
    GROUP BY t.return_status
'''), db)
q12

  return_status     cnt  avg_rating  avg_amount
0     Cancelled   23431        4.29    62854.44
1     Delivered  919722        4.31    68722.90
2      Returned   71171        4.28    62127.56

Question 13
Create a Prime Membership Analytics Dashboard analyzing Prime vs non-Prime behavior, membership value analysis, retention rates, and Prime-specific business insights.

In [31]:
q13 = pd.read_sql(text('''
    SELECT p.brand, ROUND(SUM(t.final_amount_inr),2) AS revenue
    FROM transactions t JOIN products p ON t.product_id = p.product_id
    GROUP BY p.brand
    ORDER BY revenue DESC
    LIMIT 15
'''), db)
q13

        brand       revenue
0     Samsung  1.853748e+10
1       Apple  1.464766e+10
2     OnePlus  1.108285e+10
3      Xiaomi  4.903687e+09
4      Realme  2.709280e+09
5        Vivo  2.112904e+09
6        Oppo  2.042269e+09
7      Lenovo  1.878321e+09
8   Alienware  1.493151e+09
9        ASUS  1.308069e+09
10       Acer  1.265400e+09
11        MSI  9.787917e+08
12       Dell  8.751981e+08
13         HP  8.103698e+08
14         LG  7.995502e+08

Question 14
Build a Customer Retention Dashboard showing cohort analysis, churn prediction, retention strategies effectiveness, and customer lifecycle management insights.

In [32]:
q14 = pd.read_sql(text('''
    WITH first_purchase AS (
        SELECT t.customer_id, MIN(td.year) AS cohort_year
        FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
        GROUP BY t.customer_id
    ),
    clv AS (
        SELECT customer_id, SUM(final_amount_inr) AS total_spend
        FROM transactions
        GROUP BY customer_id
    )
    SELECT fp.cohort_year, ROUND(AVG(clv.total_spend),2) AS avg_clv, COUNT(*) AS customers
    FROM first_purchase fp JOIN clv ON fp.customer_id = clv.customer_id
    GROUP BY fp.cohort_year
    ORDER BY fp.cohort_year
'''), db)
q14

    cohort_year    avg_clv  customers
0          2015  488498.27      11014
1          2016  344002.11      16529
2          2017  287640.88      23385
3          2018  251291.69      30392
4          2019  220682.21      37268
5          2020  215512.17      44000
6          2021  194698.56      42387
7          2022  152329.60      40717
8          2023  132408.16      38928
9          2024  112504.23      37183
10         2025   92133.86      23560

Question 15
Design a Demographics & Behavior Dashboard analyzing age group preferences, spending patterns, geographic behaviors, and targeted marketing opportunities.

In [33]:
q15 = pd.read_sql(text('''
    SELECT WIDTH_BUCKET(t.discount_percent, 0, 100, 5) AS discount_bucket,
           ROUND(AVG(t.quantity),2) AS avg_qty,
           ROUND(SUM(t.final_amount_inr),2) AS revenue
    FROM transactions t
    GROUP BY discount_bucket
    ORDER BY discount_bucket
'''), db)
q15

   discount_bucket  avg_qty       revenue
0                1     1.25  5.004079e+10
1                2     1.25  1.269011e+10
2                3     1.25  4.717560e+09
3                4     1.25  1.651926e+09

Question 16
Create a Product Performance Dashboard ranking products by revenue, units sold, ratings, and return rates with category-wise analysis and product lifecycle tracking.

In [34]:
q16 = pd.read_sql(text('''
    SELECT FLOOR(t.customer_rating) AS rating_band,
           COUNT(*) AS cnt,
           ROUND(AVG(t.final_amount_inr),2) AS avg_amount
    FROM transactions t
    WHERE t.customer_rating IS NOT NULL
    GROUP BY rating_band
    ORDER BY rating_band
'''), db)
q16

   rating_band     cnt  avg_amount
0          3.0  114327    59444.66
1          4.0  411248    66225.91
2          5.0  181435    77893.96

Question 17
Build a Brand Analytics Dashboard comparing brand performance, market share evolution, customer preferences, and competitive positioning across categories.

In [35]:
q17 = pd.read_sql(text('''
    SELECT order_count, COUNT(*) AS num_customers
    FROM (
        SELECT customer_id, COUNT(*) AS order_count
        FROM transactions
        GROUP BY customer_id
    ) sub
    GROUP BY order_count
    ORDER BY order_count
'''), db)
q17.head(10)

   order_count  num_customers
0            1          99567
1            2          87032
2            3          58945
3            4          37513
4            5          23222
5            6          14664
6            7           9264
7            8           5799
8            9           3558
9           10           2321

Question 18
Design an Inventory Optimization Dashboard analyzing product demand patterns, seasonal trends, inventory turnover, and demand forecasting for better inventory management.

In [37]:
q18 = pd.read_sql(text('''
    SELECT p.launch_year, td.year AS sale_year,
           ROUND(SUM(t.final_amount_inr),2) AS revenue
    FROM transactions t
    JOIN products p ON t.product_id = p.product_id
    JOIN time_dimension td ON t.date_id = td.date_id
    WHERE p.launch_year IS NOT NULL
    GROUP BY p.launch_year, td.year
    ORDER BY p.launch_year, td.year
'''), db)
q18.head(10)

   launch_year  sale_year       revenue
0         2015       2015  1.913086e+09
1         2015       2016  1.633769e+09
2         2015       2017  1.734806e+09
3         2015       2018  1.641724e+09
4         2015       2019  1.465981e+09
5         2015       2020  1.670579e+09
6         2015       2021  1.277262e+09
7         2015       2022  8.798260e+08
8         2015       2023  7.400243e+08
9         2015       2024  5.596684e+08

Question 19
Create a Product Rating & Review Dashboard analyzing rating distributions, review sentiment, correlation with sales, and product quality insights.

In [38]:
q19 = pd.read_sql(text('''
    SELECT p.category, p.brand,
           ROUND(MIN(t.original_price_inr),2) AS min_price,
           ROUND(AVG(t.original_price_inr),2) AS avg_price,
           ROUND(MAX(t.original_price_inr),2) AS max_price
    FROM transactions t JOIN products p ON t.product_id = p.product_id
    GROUP BY p.category, p.brand
    ORDER BY p.category, avg_price DESC
'''), db)
q19.head(10)

                    category      brand  min_price  avg_price  max_price
0  Electronics & Accessories      Apple    4330.27  143570.35  2316168.4
1  Electronics & Accessories         LG   28733.44  136694.17  1877935.1
2  Electronics & Accessories  Alienware   28914.41  112511.19  2097268.7
3  Electronics & Accessories       ASUS   24121.10  110601.82  1877061.5
4  Electronics & Accessories        MSI   38587.27  105429.45  1366138.3
5  Electronics & Accessories       Dell   25659.64  102980.44  2156914.5
6  Electronics & Accessories       Acer   23335.00  100085.19  2141838.8
7  Electronics & Accessories         HP   35502.79   97455.00  2093814.7
8  Electronics & Accessories    Samsung    2374.84   91984.85  2312128.0
9  Electronics & Accessories     Lenovo   25038.80   91791.30  2122327.5

Question 20
Build a New Product Launch Dashboard tracking launch performance, market acceptance, competitive analysis, and success metrics for product development teams.

In [39]:
q20 = pd.read_sql(text('''
    SELECT td.year,
           ROUND(SUM(t.final_amount_inr),2) AS revenue,
           COUNT(DISTINCT t.customer_id) AS active_customers,
           ROUND(AVG(t.final_amount_inr),2) AS avg_order_value,
           COUNT(*) AS total_orders
    FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
    GROUP BY td.year
    ORDER BY td.year
'''), db)
q20

    year       revenue  active_customers  avg_order_value  total_orders
0   2015  1.913086e+09             11014         64279.48         29762
1   2016  3.232041e+09             25273         64983.93         49736
2   2017  4.946704e+09             37130         71041.69         69631
3   2018  6.508979e+09             47791         72734.97         89489
4   2019  7.739441e+09             58500         70751.55        109389
5   2020  1.067302e+10             68978         82556.08        129282
6   2021  9.886130e+09             66393         79542.11        124288
7   2022  7.662716e+09             63772         64222.57        119315
8   2023  6.933545e+09             60978         60655.10        114311
9   2024  6.147703e+09             58369         56139.30        109508
10  2025  3.457024e+09             37148         49660.61         69613

In [40]:
VIEWS = """
CREATE OR REPLACE VIEW vw_revenue_by_year AS
SELECT td.year,
       ROUND(SUM(t.final_amount_inr),2) AS revenue,
       COUNT(*) AS orders,
       COUNT(DISTINCT t.customer_id) AS active_customers
FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
GROUP BY td.year;

CREATE OR REPLACE VIEW vw_revenue_by_month AS
SELECT td.year, td.month, td.month_name,
       ROUND(SUM(t.final_amount_inr),2) AS revenue,
       COUNT(*) AS orders
FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
GROUP BY td.year, td.month, td.month_name;

CREATE OR REPLACE VIEW vw_category_performance AS
SELECT p.category, p.subcategory,
       ROUND(SUM(t.final_amount_inr),2) AS revenue,
       COUNT(*) AS orders,
       ROUND(AVG(t.customer_rating),2) AS avg_rating
FROM transactions t JOIN products p ON t.product_id = p.product_id
GROUP BY p.category, p.subcategory;

CREATE OR REPLACE VIEW vw_brand_performance AS
SELECT p.brand,
       ROUND(SUM(t.final_amount_inr),2) AS revenue,
       COUNT(*) AS orders
FROM transactions t JOIN products p ON t.product_id = p.product_id
GROUP BY p.brand;

CREATE OR REPLACE VIEW vw_geographic_performance AS
SELECT c.customer_state, c.customer_city, c.customer_tier,
       ROUND(SUM(t.final_amount_inr),2) AS revenue,
       COUNT(DISTINCT c.customer_id) AS customers
FROM transactions t JOIN customers c ON t.customer_id = c.customer_id
GROUP BY c.customer_state, c.customer_city, c.customer_tier;

CREATE OR REPLACE VIEW vw_customer_rfm AS
WITH ref AS (
    SELECT MAX(td.full_date) AS max_date
    FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
)
SELECT t.customer_id,
       (SELECT max_date FROM ref) - MAX(td.full_date) AS recency_days,
       COUNT(DISTINCT t.transaction_id) AS frequency,
       ROUND(SUM(t.final_amount_inr),2) AS monetary
FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
GROUP BY t.customer_id;

CREATE OR REPLACE VIEW vw_payment_trends AS
SELECT td.year, t.payment_method,
       ROUND(SUM(t.final_amount_inr),2) AS revenue,
       COUNT(*) AS txn_count
FROM transactions t JOIN time_dimension td ON t.date_id = td.date_id
GROUP BY td.year, t.payment_method;

CREATE OR REPLACE VIEW vw_delivery_performance AS
SELECT c.customer_tier, c.customer_state,
       ROUND(AVG(t.delivery_days),2) AS avg_delivery_days,
       ROUND(AVG(t.customer_rating),2) AS avg_rating
FROM transactions t JOIN customers c ON t.customer_id = c.customer_id
WHERE t.delivery_days IS NOT NULL
GROUP BY c.customer_tier, c.customer_state;

CREATE OR REPLACE VIEW vw_returns_analysis AS
SELECT p.category, t.return_status,
       COUNT(*) AS cnt,
       ROUND(AVG(t.customer_rating),2) AS avg_rating
FROM transactions t JOIN products p ON t.product_id = p.product_id
GROUP BY p.category, t.return_status;

CREATE OR REPLACE VIEW vw_executive_summary AS
SELECT
    (SELECT ROUND(SUM(final_amount_inr),2) FROM transactions) AS total_revenue,
    (SELECT COUNT(DISTINCT customer_id) FROM transactions) AS total_customers,
    (SELECT ROUND(AVG(final_amount_inr),2) FROM transactions) AS avg_order_value,
    (SELECT COUNT(*) FROM transactions) AS total_orders,
    (SELECT COUNT(*) FROM transactions WHERE is_festival_sale) AS festival_orders;
"""

with db.begin() as conn:
    for stmt in VIEWS.split(";"):
        if stmt.strip():
            conn.execute(text(stmt))

print("Views created: vw_revenue_by_year, vw_revenue_by_month, vw_category_performance,",
      "vw_brand_performance, vw_geographic_performance, vw_customer_rfm,",
      "vw_payment_trends, vw_delivery_performance, vw_returns_analysis, vw_executive_summary")

Views created: vw_revenue_by_year, vw_revenue_by_month, vw_category_performance, vw_brand_performance, vw_geographic_performance, vw_customer_rfm, vw_payment_trends, vw_delivery_performance, vw_returns_analysis, vw_executive_summary

In [41]:
# Quick sanity check on the views
pd.read_sql(text("SELECT * FROM vw_executive_summary"), db)

,total_revenue,total_customers,avg_order_value,total_orders,festival_orders
0,6.910039e+10,345363,68124.57,1014324,314789

In [17]:
q14 = pd.read_sql(text('''
    WITH first_purchase AS (
        SELECT t.customer_id, MIN(td.year) AS cohort_year
        FROM fact_sales t JOIN dim_time td ON t.date_id = td.date_id
        GROUP BY t.customer_id
    ),
    clv AS (
        SELECT customer_id, SUM(final_amount_inr) AS total_spend
        FROM fact_sales
        GROUP BY customer_id
    )
    SELECT fp.cohort_year, (AVG(clv.total_spend),2) AS avg_clv, COUNT(*) AS customers
    FROM first_purchase fp JOIN clv ON fp.customer_id = clv.customer_id
    GROUP BY fp.cohort_year
    ORDER BY fp.cohort_year
'''), db)
q14

    cohort_year                 avg_clv  customers
0          2015   (490973.5037679324,2)      11014
1          2016  (345826.96247322706,2)      16529
2          2017  (289212.84981782996,2)      23385
3          2018  (252584.25938470813,2)      30392
4          2019  (221697.96763818865,2)      37268
5          2020  (216557.56859159024,2)      44000
6          2021  (195716.67787977398,2)      42387
7          2022   (153101.9520816866,2)      40717
8          2023  (133027.43738106271,2)      38928
9          2024   (113073.1449568349,2)      37183
10         2025   (92610.53322877706,2)      23560